[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = ".netlify/functions-internal"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  publish = "build"
  autoLaunch = true

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir    = "build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  ignorePeriod = 0 
